# Generated by Django 4.1.3 on 2022-12-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.IntegerField(choices=[(0, 'English'), (1, 'Czech')], default=0),
        ),
    ]
