# Generated by Django 4.1.3 on 2023-01-27 16:54

import blog.models
from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='art',
            field=pictures.models.PictureField(aspect_ratios=[None], blank=True, breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to=blog.models.Post.art_dir_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'Post'), (1, 'Fiction'), (2, 'Chords')], default=0),
        ),
    ]
