# Generated by Django 4.1.3 on 2022-12-06 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_picture_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='album',
            name='preview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preview', to='media.picture'),
        ),
    ]
